services:
  base-pnpm:
    image: node-with-pnpm:latest
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.node-with-pnpm
  pnpm:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.pnpm
      additional_contexts:
        node-with-pnpm: "service:base-pnpm"
    volumes:
      - ./frontend:/app
    depends_on:
      - base-pnpm

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfiles/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfiles/Dockerfile.dev
      additional_contexts:
        node-with-pnpm: "service:base-pnpm"
    ports:
      - 3000:3000
    depends_on:
      - base-pnpm
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  database: 
    image: "postgres:17.5"
    environment:
      POSTGRES_PASSWORD: Ahmedxd1
      POSTGRES_USER: ahmed 
      POSTGRES_DB: subscriptions 
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data:
  node_modules: