from node:25

shell ["/bin/bash", "-c"]

arg PNPM_HOME="/pnpm"

env PNPM_HOME=${PNPM_HOME}
env PATH="$PNPM_HOME:$PATH"

run set -o pipefail && wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -